# Generated by Django 5.2.17 on 2026-09-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('runtime_minutes', models.IntegerField(verbose_name='Duración (min)')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('poster_url', models.URLField(max_length=500, verbose_name='URL del Póster')),
                ('cult_status', models.TextField(verbose_name='Estatus de Culto')),
                ('format_type', models.CharField(max_length=50, verbose_name='Formato (35mm/16mm/etc)')),
                ('audio', models.CharField(max_length=100, verbose_name='Audio')),
                ('categorias', models.ManyToManyField(related_name='peliculas', to='catalogo.categoria')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='principal.director')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
    ]
