# Generated by Django 5.2.17 on 2026-09-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=150)),
                ('obra_destacada', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
    ]
